//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberBoss.Exception {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarberBoss.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data não pode ser no futuro.
        /// </summary>
        public static string DataNaoFututo {
            get {
                return ResourceManager.GetString("DataNaoFututo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Emailjá esta cadastrado.
        /// </summary>
        public static string EmailCadastrado {
            get {
                return ResourceManager.GetString("EmailCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email invalido.
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email ja cadastrado.
        /// </summary>
        public static string EmailJaCadastrado {
            get {
                return ResourceManager.GetString("EmailJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email não pode ser vazio.
        /// </summary>
        public static string EmailVazio {
            get {
                return ResourceManager.GetString("EmailVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email e/ou senha inválido.
        /// </summary>
        public static string LoginNaoAutorizado {
            get {
                return ResourceManager.GetString("LoginNaoAutorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome não pode ser vazio.
        /// </summary>
        public static string NomeVazio {
            get {
                return ResourceManager.GetString("NomeVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de pagamento inválido.
        /// </summary>
        public static string PagamentoInválido {
            get {
                return ResourceManager.GetString("PagamentoInválido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro não foi encontrado.
        /// </summary>
        public static string RegistroNaoEncontrado {
            get {
                return ResourceManager.GetString("RegistroNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha deve ser igual senha atual.
        /// </summary>
        public static string SenhaDeveSerIgual {
            get {
                return ResourceManager.GetString("SenhaDeveSerIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha deve conter caracterespecial.
        /// </summary>
        public static string SenhainvalidaCaracterEspecial {
            get {
                return ResourceManager.GetString("SenhainvalidaCaracterEspecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha deve conter caracter numerico.
        /// </summary>
        public static string SenhainvalidaCaracterNumerico {
            get {
                return ResourceManager.GetString("SenhainvalidaCaracterNumerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha deve conter ao menos uma letra maiuscula e uma minuscula.
        /// </summary>
        public static string SenhainvalidaLetraMaiuscula {
            get {
                return ResourceManager.GetString("SenhainvalidaLetraMaiuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha deve conter mais que 6 caracteres.
        /// </summary>
        public static string SenhainvalidaMaiorSeisCaracter {
            get {
                return ResourceManager.GetString("SenhainvalidaMaiorSeisCaracter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha não pode ser vazia.
        /// </summary>
        public static string SenhaVazia {
            get {
                return ResourceManager.GetString("SenhaVazia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tag não suportada.
        /// </summary>
        public static string TagNaoSuportada {
            get {
                return ResourceManager.GetString("TagNaoSuportada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor deve ser maior que zero.
        /// </summary>
        public static string ValorMaiorQueZero {
            get {
                return ResourceManager.GetString("ValorMaiorQueZero", resourceCulture);
            }
        }
    }
}
